### ISSUE TITLE
pong server 빌드 시 오류

### ISSUE THREAD

**Issue by dkmoon** [iFunEngine/iFunEngine#158]
_2019년 10월 16일 youngjupark 님이 올리신 질문입니다._

```
Traceback (most recent call last): 
File "/usr/bin/funapi_launcher_generator", line 181, in <module> main(sys.argv) 
File "/usr/bin/funapi_launcher_generator", line 173, in main output_content = t.render(params) 
File "/usr/lib/python2.7/dist-packages/jinja2/environment.py", line 1008, in render return self.environment.handle_exception(exc_info, True) 
File "/usr/lib/python2.7/dist-packages/jinja2/environment.py", line 780, in handle_exception reraise(exc_type, exc_value, tb) 
File "<template>", line 59, in top-level template code UnicodeDecodeError: 'ascii' codec can't decode byte 0xeb in position 17: ordinal not in range(128) 
make[2]: * [pongcs.matchmaker-local] Error 1 
make[2]: Deleting file 'pongcs.matchmaker-local' 
CMakeFiles/Makefile2:141: recipe for target 'CMakeFiles/internal_create_launchers.dir/all' failed 
make[1]: [CMakeFiles/internal_create_launchers.dir/all] Error 2 Makefile:151: recipe for target 'all' failed make: * 
[all] Error 2
    ========== 빌드: 0개 성공, 1개 실패, 0개 최신 상태, 0개 건너뜀 ==========

사용자 지정 명령 실패(종료 코드: 2)
```

빌드하면 위 에러가 발생하는 이유를 알 수 있을까요? 다른 설정을 해줘야되는게 있는지 궁금합니다.

**Comment by dkmoon** [comment]
https://github.com/iFunFactory/game-pong-server-csharp 프로젝트에 대한 문의가 맞으실까요? 빌드를 진행하시는 개발환경에 대해서 알려주시면 확인 후에 답변드리도록 하겠습니다.

**Comment by dkmoon** [comment]
네 맞습니다. Ubuntu 18.04 환경이며, MonoDevelop 사용하고 있습니다. c#입니다.

현재 문제점

1. funapi-leaderboard 설치 후 환경설정 후 Manifest.json을 수정하는 과정에서 읽기전용 파일이라고 하며, 수정이 불가능합니다.

1. 해당 깃 허브에 있는 파일을 다운 후 MonoDevelop으로 파일을 연 후 빌드를 해보았으나, 위 내용과 같은 오류가 발생합니다.

**Comment by dkmoon** [comment]
리눅스 커맨드 라인에서 `funapi_select_repo` 명령의 실행 결과도 올려주시기 바랍니다. 발생하는 문제에 대해서 확인 후에 답변드리도록 하겠습니다. 감사합니다.

**Comment by dkmoon** [comment]
```
Current repository: stable Current package: fuapi1-runtime_1.0.0-4339bionic: stable
```
입니다.

**Comment by dkmoon** [comment]
코드를 보니 `lobby_server.cs` 에서 line30, line37에 보면 `ActivityLog.SessionOpened`, `ActivityLog.SessionClosed` 에 대한 정의가 포함되지 않았다고 나오며,

line155 User이름이 현재 컨텍스트에 없다고 나옵니다.

line 167에도 마찬가지로 `ActivityLog.PlayerLoggedIn` 에 대한 정의가 포함되지 않다고 나오네요

**Comment by dkmoon** [comment]
지금 보니까 cs파일들이 제대로 적용이 안된듯하네요 다시 재적용 후 확인해보겠습니다.
