### ISSUE TITLE
아이펀 엔진 업데이트 후 빌드 오류

### ISSUE THREAD

**Issue by dkmoon** [iFunEngine/iFunEngine#193]
현재 ubuntu 1604.6 LTS + vs2015 Remote로 개발중입니다. 기존에 사용하던 v1.0.0-4096 (2019-06-04) 에서 v1.0.0-4991 (2020-02-07) 업데이트 후 빌드 오류가 발생합니다.

```
[ 31%] Generating /home/administrator/projects/aid-server/AID-Server/aid-source/src/aid_object.h, /home/administrator/projects/aid-server/AID-Server/aid-source/src/object_model/aid_object.cc, /home/administrator/projects/aid-server/AID-Server/aid-source/src/aid_object.py

1> Traceback (most recent call last):
1> File "/usr/bin/funapi_object_generator", line 1034, in <module>
1> Traceback (most recent call last):
1> File "/usr/bin/funapi_object_generator", line 1034, in <module>
1> main(sys.argv)
1> main(sys.argv)
1> File "/usr/bin/funapi_object_generator", line 841, in main
1> File "/usr/bin/funapi_object_generator", line 841, in main
1> json_objects = read_object_definition_json(FLAGS.definition_dir)
1> json_objects = read_object_definition_json(FLAGS.definition_dir)
1> File "/usr/bin/funapi_object_generator", line 126, in read_object_definition_json
1> File "/usr/bin/funapi_object_generator", line 126, in read_object_definition_json
1> except json.decoder.JSONDecodeError as error:
1> except json.decoder.JSONDecodeError as error:
1> AttributeError: 'module' object has no attribute 'JSONDecodeError'AttributeError: 'module' object has no attribute 'JSONDecodeError'
1>
1> src/CMakeFiles/aid.dir/build.make:62: recipe for target '/home/administrator/projects/aid-server/AID-Server/aid-source/src/aid_object.h' failed
1> make[2]: * [/home/administrator/projects/aid-server/AID-Server/aid-source/src/aid_object.h] Error 1
1> make[2]: * [/home/administrator/projects/aid-server/AID-Server/aid-source/src/aid_object.h] Error 1
1> CMakeFiles/Makefile2:232: recipe for target 'src/CMakeFiles/aid.dir/all' failed
1> Makefile:138: recipe for target 'all' failed
1> make[1]: * [src/CMakeFiles/aid.dir/all] Error 2
1> make: * [all] Error 2
1> make[1]: * [src/CMakeFiles/aid.dir/all] Error 2
1> make: * [all] Error 2 1>
```

**Comment by dkmoon** [comment]
오류 메시지가 정상적으로 출력되어야하나 그렇지 않은 부분이 있어서 불편을 드려 죄송하게 생각합니다.

위의 log 상으로 확인한 바로는 (근 시일에) 소스 디렉터리 이하의 src/object_model 밑에 있는 JSON 파일을 수정한 것 같습니다. 수정 후 결과로,

* 해당 파일을 UTF-8 형식이 아닌 것으로 저장한 경우
* (주석을 제외한) 해당 파일의 내용이 JSON 포맷에 맞지 않는 부분이 있는 경우

위의 문제가 생긴 것 같습니다. 위 내용 확인 부탁드리겠습니다. 오류 메시지 출력은 이후 릴리즈에서 수정할 예정입니다.

**Comment by dkmoon** [comment]
해결되었습니다. src/object_model 의 json 파일이 UTF-8(BOM)으로 저장되어있었습니다. 감사합니다^^.
