### ISSUE TITLE
dedicate scale out 방법 문의

### ISSUE THREAD

**Issue by dkmoon** [iFunEngine/iFunEngine#227]
_2020년 4월 20일 newtrocode 님이 올리신 질문입니다._

안녕하세요.

AWS EC2 에 game server와 dedicate host manager, dedicate server (unity), redis 를 1개의 인스턴스(이하 A)에 구성을 했습니다.

게임 시작시 데디케이트가 정상적으로 spawn 되어 게임이 진행되는 것을 확인 했습니다.

추가적으로 EC2에 1대의 인스턴스(이하 B)를 생성해서 dedicate host manager를 설치하고

`/etc/funapi-dedicated-server-host/funapi-dedicated-server-host.flag` 에서

redis_host 정보를 수정해서, 다음과 같이 dedicate host manager를 시작했습니다.

```
sudo systemctl start funapi-dedicated-server-host
```

하지만 ps 로 확인을 해도 funapi_dedicated_server 가 보이지 않고,

redis에도 추가된 서버 정보가 없습니다.

제가 생각하고 있는게 정상적이 dedicate scale out 방식인지 궁금합니다.

추가적으로 해야하는게 있다면 어떤것인지 가이드 부탁드립니다.

감사합니다.

**Comment by dkmoon** [comment]
위 방식이 일반적인 데디케이티드 서버 스케일아웃 시나리오입니다. (다만 redis 서버는 추후 확장을 위해 별개의 인스턴스나 서비스를 사용하는 것이 좋습니다)

`sudo systemctl status funapi-dedicated-server-host` 를 Host B에서 실행해서, 정상적으로 실행되고 있는지 확인해보셔야 할 것 같습니다.

**Comment by dkmoon** [comment]
답변 감사합니다. 상태를 체크하니 python 모듈 관련 오류가 있음을 확인했습니다.

mono와 dedicate host manager만 설치 했는데,

ifunengine를 설치(`sudo apt-get install -y funapi1-dev`)하니 해결이 됐습니다.

추가적으로 질문이 더 있습니다.

1. 아이펀 엔진에 dedicate host manager가 종속성이 있는게 맞는건가요?

1. dedicate host manager가 있는 모든 인스턴스 마다 `account.ilf` 도 복사 해야 하나요?

**Comment by dkmoon** [comment]
dedicated server host manager는 의존성을 모두 포함하고 있어서 `funapi1-dev` 패키지는 필요하지 않아야 합니다. 습니다. 위에서 언급한 실패 로그를 알려주시면 혹시 빠진 의존성이 있는지 확인해보겠습니다.

**Comment by dkmoon** [comment]
변 감사합니다.

로그는 다음과 같습니다.

```
> Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 163, in _run_module_as_main
    mod_name, _Error)
  File "/usr/lib/python2.7/runpy.py", line 111, in _get_module_details
    __import__(mod_name)  # Do not catch exceptions initializing package
  File "/usr/lib/python2.7/dist-packages/funapi_dedicated_server/__init__.py", line 44, in <module>
    from builtins import range  # nopep8 pylint: disable=W0622,wrong-import-position
  File "/usr/lib/python2.7/dist-packages/gevent/builtins.py", line 93, in __import__
    result = _import(*args, **kwargs)
ImportError: No module named builtins
```

**Comment by dkmoon** [comment]
`python-future` 패키지를 추가로 설치 해 주시면 funapi1-dev 패키지 없이도 동작할 것 같습니다.

* Ubuntu 16.04, 18.04: `sudo apt-get install python-future`
* Ubuntu 20.04: `sudo apt-get install python3-future`
* CentOS 7: `sudo yum install python-future`
* CentOS 8: `sudo yum install python3-future`
